version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
#    expose:
#      - "8080"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
